sonar.projectName=GestionDeProjets
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/**/*.spec.ts

sonar.java.binaries=backend/target/classes
sonar.java.libraries=backend/target/dependency/*.jar

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/.angular/**,frontend/src/**/*.spec.ts
