services:
  gestionprojets-phpmyadmin:
    image: phpmyadmin:latest
    container_name: gestionprojets-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 512M
    ports:
      - "127.0.0.1:8084:80"
    networks:
      - gestion-network

networks:
  gestion-network:
    external: true
